### ISSUE TITLE
Line not continuous

### ISSUE THREAD

**Issue by zachberger** [mozilla/metrics-graphics#292] opened 2014-12-30 06:09 UTC
Several gaps are apparent in the line 

![screen shot 2014-12-30 at 1 07 28 am](https://cloud.githubusercontent.com/assets/1634878/5576120/6eca3650-8fc0-11e4-9f85-2d0ae31aeaec.png)

**Comment by almossawi** [comment] 2015-01-02 20:58
Closing, as I'm unable to reproduce the bug. If you're facing the same issue with other charts that created in d3.js then perhaps file a bug [here](https://github.com/mbostock/d3).

**Closed by almossawi** 2015-01-02 20:58 UTC
