### ISSUE TITLE
How to remove/reduce large gap on left side of y-axis?

### ISSUE THREAD

**Issue by brylie** [mozilla/metrics-graphics#485] opened 2015-08-20 06:57 UTC
There is a large gap on the y-axis of some charts:
![activity-chart-gap-and-spillover](https://cloud.githubusercontent.com/assets/17307/9377439/bf935788-4721-11e5-81ce-fdae7128ebca.jpg)

This affects the trend line, and makes it difficult to interpret values outside of the y-axis labels.

How can I remove the gap on the left, as well as spillover on right side?

**Comment by almossawi** [comment] 2015-09-01 03:46
@brylie I'm terribly sorry for the late reply. I've been really behind on emails lately.

@hamilton The least-squares line starts at the first tick rather than the left edge. Is this by design?

**Comment by brylie** [comment] 2015-09-01 08:42
@almossawi thanks for your follow up. I really appreciate how consistent you have been with support requests, and can relate to the inbox overflow :-)

For what it's worth, the chart has gotten worse since adding more data, with a larger gap on the left side:

![activity-chart-gap-increased](https://cloud.githubusercontent.com/assets/17307/9599680/6fed0b26-509e-11e5-9601-163499e8be4f.jpg)

**Comment by almossawi** [comment] 2015-09-01 20:31
``xax_start_at_min`` will set the first tick to the left edge.

@hamilton This latest commit makes the line span the range of the data rather than the ticks.

**Comment by brylie** [comment] 2015-09-02 05:46
@almossawi the trendline fix looks great:
![screenshot-of-trendline-with-gaps](https://cloud.githubusercontent.com/assets/17307/9623834/03780f5c-514f-11e5-9ea6-c42ae5e8a373.jpeg)

I am still noticing a left-side gap and right-side spillover, but will test the configuration parameter you mentioned.

**Comment by brylie** [comment] 2015-09-02 05:51
@almossawi `xax_start_at_min` works as the name denotes:
![screenshot-of-trendline-with-right-side-gap](https://cloud.githubusercontent.com/assets/17307/9623865/9a476ce8-514f-11e5-981c-eafe12b5657d.jpeg)

Is there a way to tell the x-axis to end at max? It may be worth considering setting these to `true` by default, as it takes a bit of unneeded effort to interpret the charts when the data points overflow the axis labels.

**Comment by almossawi** [comment] 2015-09-02 05:54
Working on it https://github.com/mozilla/metrics-graphics/issues/456 :)

**Comment by almossawi** [comment] 2015-10-15 20:47
Being tracked in #456 and #489, so I'll go ahead and close this.

**Closed by almossawi** 2015-10-15 20:47 UTC
