### ISSUE TITLE
Too many space beween graph area and y-axis

### ISSUE THREAD

**Issue by harobed** [mozilla/metrics-graphics#257] opened 2014-12-03 16:23 UTC
Too many space beween graph area and y-axis

![metrics-graphics-too-many-space-between-y-axis-and-grapharea](https://cloud.githubusercontent.com/assets/230143/5283928/27168c14-7b11-11e4-98c8-b67ca7bbf398.png)

**Comment by almossawi** [comment] 2015-01-08 19:55
@harobed If you wouldn't mind sharing your dataset as I'm unable to reproduce the bug.

**Comment by mlem** [comment] 2015-01-28 22:21
![broken_x_axis](https://cloud.githubusercontent.com/assets/1065169/5948284/f7253230-a743-11e4-8c84-30a6d673934d.PNG)
On Chrome Version 40.0.2214.93 m
On Windows 7 64bit

At first I thought that overflowing diagrams are a serious bug. I wanted to see if it was reported and found this issue.

At least you could mention on your example site that it is overflowing by design...

It shouldn't overflow to the left though.

**Comment by almossawi** [comment] 2015-01-30 07:38
@mlem To be clear, the highlighted marker is the start-of-year marker, which you can disable by setting ``show_years`` to false or setting the opacity of ``.mg-year-marker line`` to 0. The axis starts right where the line begins.

As noted above, axis line does not cover the entire scale by design, though I'd like to look into that next week, since having ticks start so far to the right on occasion can be a bit of an eyesore.

**Comment by almossawi** [comment] 2015-02-12 20:39
Closing, as I'm unable to reproduce the issue in the original screenshot. As mentioned earlier, the fact that axes don't cover the entire width or height of the container is by design.

You're welcome to submit a PR if you have other thoughts and we'd be happy to review it.

**Closed by almossawi** 2015-02-12 20:39 UTC

**Comment by passcod** [comment] 2015-02-12 22:15
> As noted above, axis line does not cover the entire scale by design, though I'd like to look into that next week, __since having ticks start so far to the right on occasion can be a bit of an eyesore.__

_(emphasis mine)_

Is there an issue opened up for this?

**Comment by almossawi** [comment] 2015-02-12 22:17
@passcod Feel free to open an issue. Thanks.
