### ISSUE TITLE
specify what the default interpolation is in the documentation

### ISSUE THREAD

**Issue by openjck** [mozilla/metrics-graphics#713] opened 2016-09-08 19:17 UTC
### Steps to reproduce

Download and open this [HTML document](https://gist.github.com/openjck/7ecf456c3e61079470f57c650cdd5400)
### Actual result

The line curves left between x=1 and x=2.
### Expected result

There should be a straight line between x=1 and x=2. This is sort of a contrived example, but I've also seen it happen with real data in more subtle ways. I think [this](https://cloud.githubusercontent.com/assets/933396/18363235/4637bc7c-75d7-11e6-80da-208fe3d3b2cf.png) might also be caused by the same bug.

**Comment by FaKeller** [comment] 2017-01-09 09:22
I've just made a JSFiddle of the above reproduction steps to demonstrate the behavior: 
https://jsfiddle.net/20nx5ett/

I can confirm having the same issue with time series data in a recent project of mine, where the current behavior is even more misleading.

**Comment by FaKeller** [comment] 2017-01-09 10:13
Digging deeper into the topic I just discovered the `interpolate` option of MG, which [according to the docs](https://github.com/mozilla/metrics-graphics/wiki/Graphic#interpolate) is set to `d3.curveCatmullRom.alpha(0)` by default. That interpolation method causes the curves' behavior as described in this issue, especially for sparse data sets.

To produce a monotone line the `interpolate` option can be set to `d3.curveMonotoneX` (see [this updated fiddle](https://jsfiddle.net/9rkyhf97/1/)). Other interpolation options are described [in the D3 docs](https://github.com/d3/d3-shape#curves) in detail.

I guess the issue is not the interpolation itself but the documentation. I guess it would be worth to point out this behavior somewhere in the docs, as [most time-series examples on the website](http://metricsgraphicsjs.org/examples.htm) use the default interpolation while looking good, leading to the assumption that the MG defaults are suited for time-series data.

**Comment by hamilton** [comment] 2017-12-13 23:23
I believe the default interpolation is already set in the docs, so I'm going to close this (old) issue. Apologies for delay.

**Closed by hamilton** 2017-12-13 23:23 UTC
Labels: docs
