### ISSUE TITLE
Multi-line charts link inconsistently

### ISSUE THREAD

**Issue by bsmedberg** [mozilla/metrics-graphics#553] opened 2015-11-23 14:42 UTC
I have two linked charts:
Chart A: two counts
Chart B: a single rate

When I hover the first line of chart A it links with chart B. But when I hover the second line of chart A, nothing happens in chart B. This is weirdly inconsistent.

**Comment by hamilton** [comment] 2015-11-23 17:16
Could you clarify what you mean by a 'single rate'? Do you mean you have a chart with two lines (A), and a chart with one line (B)?

**Comment by bsmedberg** [comment] 2015-11-23 18:56
Yes. In reality it's much more complex, I have 7 graphs with between 1 and 5 lines that should all be linked.

**Comment by hamilton** [comment] 2015-11-23 19:27
Gotcha. I think @almossawi has implemented something that should make this work, but he'd know more than I would. At any rate, we can definitely use this example to improve the API & smooth out this rough edge.

**Comment by hamilton** [comment] 2015-11-23 19:37
@bsmedberg now that the caffeine is hitting my blood stream, I'm assuming the issue is some of these graphs have all 5 lines, others have less than 5, but the ones with less than five may have different lines available, making the positional aspect of this problematic.

So, graph 1 may have all 5 lines, graph 2 may have the second and fourth line that is present in the first graph.

Is this the right characterization?

**Comment by bsmedberg** [comment] 2015-11-23 21:41
Correct. There is no relationship between the first line in graph A and the first line in graph B.
Try the rollovers at http://bsmedberg.github.io/telemetry-dashboard/new-pipeline/crash-summary.html

**Comment by hamilton** [comment] 2017-12-13 21:34
Closing this for now, since I think we lost the thread two years ago.

**Closed by hamilton** 2017-12-13 21:34 UTC
